name: Build React app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify build folder exists
        run: if [ ! -d "build" ]; then echo "Build directory does not exist"; exit 1; fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
            name: build-output
            path: build/